services:
  postgres:
    volumes:
      # Use configurable data path for Raspberry Pi SSD storage
      - ${DATA_PATH:-./data}/postgres:/var/lib/postgresql/data
    environment:
      # Production optimizations
      POSTGRES_INITDB_ARGS: "--data-checksums"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  graphql:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  mcp:
    environment:
      PYTHONUNBUFFERED: 1
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
