"""Initial schema with integer IDs

Revision ID: 6e6e5fee3979
Revises: 
Create Date: 2025-10-25 14:17:11.740577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6e5fee3979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type_kind', sa.Text(), nullable=False),
    sa.Column('is_action', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint("type_kind IN ('base', 'trait')", name='check_type_kind'),
    sa.ForeignKeyConstraint(['parent_id'], ['model_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attribute_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.CheckConstraint("value_type IN ('string', 'number', 'datetime', 'boolean', 'vector')", name='check_value_type'),
    sa.ForeignKeyConstraint(['model_type_id'], ['model_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_type_id', 'key', name='unique_attribute_definition')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_type_id'], ['model_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_model_type_id', sa.Integer(), nullable=False),
    sa.Column('to_model_type_id', sa.Integer(), nullable=False),
    sa.Column('relation_name', sa.Text(), nullable=False),
    sa.Column('multiplicity', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_model_type_id'], ['model_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_model_type_id'], ['model_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_model_type_id', 'to_model_type_id', 'relation_name', name='unique_relationship_type')
    )
    op.create_table('attributes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('attribute_definition_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Integer(), nullable=True),
    sa.Column('value_time', sa.DateTime(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_vector', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_definition_id'], ['attribute_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'attribute_definition_id', 'value_text', 'value_number', 'value_time', 'value_bool', name='unique_attribute_value')
    )
    op.create_table('embeddings',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('relation_attribute_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_type_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.CheckConstraint("value_type IN ('string', 'number', 'datetime', 'boolean', 'vector')", name='check_relation_value_type'),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_type_id', 'key', name='unique_relation_attribute_definition')
    )
    op.create_table('relations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_type_id'], ['relationship_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trait_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('trait_type_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_type_id'], ['model_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'trait_type_id', name='unique_trait_assignment')
    )
    op.create_table('relation_attributes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_attribute_definition_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Integer(), nullable=True),
    sa.Column('value_time', sa.DateTime(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_vector', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['relation_attribute_definition_id'], ['relation_attribute_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id', 'relation_attribute_definition_id', 'value_text', 'value_number', 'value_time', 'value_bool', name='unique_relation_attribute_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_attributes')
    op.drop_table('trait_assignments')
    op.drop_table('relations')
    op.drop_table('relation_attribute_definitions')
    op.drop_table('embeddings')
    op.drop_table('attributes')
    op.drop_table('relationship_type')
    op.drop_table('models')
    op.drop_table('attribute_definitions')
    op.drop_table('model_types')
    # ### end Alembic commands ###